#!/usr/bin/env bash
# ============================================================================
# tools/fontgen/regen_shipped.sh — regenerate the shipped bitmap fonts.
# Rebuilds the NORMALISED shipped fonts (mxbmrp3_data/fonts/*.fnt) from the
# source .ttf under mxbmrp3_data/web/fonts — consistent size/width/vertical position,
# at the normalised 135px cell (high atlas resolution so text stays crisp when a
# HUD draws it larger than the cell — high-DPI, scaled-up widgets like the speedo).
# EVERY shipped font is normalised, RobotoMono-Regular included. It was the one
# exception — kept as raw fontgen output to be test.sh's baseline — but it is
# also the default for Normal and Digits, so the single un-normalised face was
# the one most users read: ~3% wider per digit than the layout reserves, which
# overran long lines and made Normal and Strong measure differently in the same
# column. The raw artefact test.sh needs now lives in tools/fontgen/
# testdata/, where nothing renders it.
#
# NORMALISATION is `normalize = 1`: cell 135, digit-advance 0.489, centred -- so
# every shipped font renders numbers at the same size, width and vertical position
# and a font swap does not reflow a HUD. The cell height is the atlas RESOLUTION,
# not the on-screen size: the renderer scales by `size * screenH / cellH`, so a
# 135px cell keeps text crisp when a HUD draws it larger than the cell. The atlas
# auto-grows to 2048^2 to hold it.
#
# TO ADD OR REPLACE ONE font without regenerating the rest: drop the .ttf in
# mxbmrp3_data/web/fonts/, run
#   tools/fontgen/mxbmrp3_fontgen <font>.ttf mxbmrp3_data/fonts/<font>.fnt
# and commit the .fnt. (This text lived in CLAUDE.md, which is read in full before
# every task and charged for it; a tool recipe belongs with the tool.)
# ============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/../.." && pwd)"
WEB="${ROOT}/mxbmrp3_data/web/fonts"
OUT="${ROOT}/mxbmrp3_data/fonts"
TMP="$(mktemp -d)"; trap 'rm -rf "${TMP}"' EXIT

"${HERE}/build.sh" >/dev/null

# name|file   (name is the display name stored in the .fnt)
# EVERY .fnt in mxbmrp3_data/fonts has a row here, so a re-run REPRODUCES the
# shipped set byte for byte and changes nothing unless a .ttf did. Two fonts were
# missing for a while and were regenerated by hand instead -- harmless in the
# event (their metrics matched; only this list had drifted) but it left the
# header's "every shipped font is normalised" unverifiable by running the script,
# which is the only way anyone would check it. Both have since been removed with
# the themes that brought them; the lesson is why this list is exhaustive.
#
# `name` is the display string stored in the .fnt and NOTHING READS IT: fonts are
# identified by file stem, and the picker generates its label from that stem
# (AssetManager::discoverFonts). So a row's name matches whatever its committed
# file already carries, odd spellings included -- idempotence is worth more here
# than a tidier string nobody sees.
NORMALISED=(
  "Audiowide Regular|Audiowide-Regular"
  "Enter Sansman Italic|EnterSansman-Italic"
  "Fuzzy Bubbles Regular|FuzzyBubbles-Regular"
  "IBM Plex Mono Regular|IBMPlexMono-Regular"
  "IBM Plex Sans Regular|IBMPlexSans-Regular"
  "IBM Plex Sans SemiBold|IBMPlexSans-SemiBold"
  "Roboto Mono Bold|RobotoMono-Bold"
  "Roboto Mono Regular|RobotoMono-Regular"
  "Tiny5 Regular|Tiny5-Regular"
)
for entry in "${NORMALISED[@]}"; do
    name="${entry%%|*}"; file="${entry##*|}"
    cat > "${TMP}/f.cfg" <<EOF
name = ${name}
code_page = 1252
char_start = 32
char_end = 255
bitmap_x = 512
bitmap_y = 512
normalize = 1
filename = ${WEB}/${file}.ttf
EOF
    "${HERE}/mxbmrp3_fontgen" "${TMP}/f.cfg" "${OUT}/${file}.fnt"
done
echo "regenerated the normalised fonts in ${OUT}"
